# I could have sworn I tried something like this earlier and it didn't work,
# but at the moment I don't see any reason to prefer the more complex
# solution at `../Makefile` over this.

a.csv: a.py
	touch a.csv
a.py: b.py
	touch a.py
b.py:
	touch b.py
